name: lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ecs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rector Action
        uses: zingimmick/rector-action@0.0.1
        with:
          args: --dry-run

      - name: Easy Coding Standard Action
        uses: zingimmick/ecs-action@0.0.3
