name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    uses: zingimmick/.github/.github/workflows/auto-merge.yml@main
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
